[build]
  command = "npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
